import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai"
import Image from "next/image";
import photo from '../public/pic.jpeg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Victor Marin Viloria | Frontend Developer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='font-poppins text-xl'>Victor Marin Viloria</h1>
            <ul className=' flex items-center'>
              <li className='cursor-pointer text-2xl'><BsFillMoonStarsFill /></li>
              <li><a className='bg-cyan-500 text-white px-4 py-2 rounded-md ml-8' href="#">My CV</a></li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Victor Marin Viloria</h2>
            <h3 className='text-2xl py-2'>Developer and Teacher.</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Frontend Developer specialized in e-learning.
              Drop a line below and let's talk! :)
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube/> 
          </div>

          <div className='relative rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden'>
            <Image src={photo} layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Since the beginning of my journey as a developer, 
              I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
        </section>


      </main>

      {/* <h1></h1> */}

    </div>
  )
}
