import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai"
import Image from "next/image";
import photo from '../public/pic.jpeg'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from "react"

export default function Home() {

  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Victor Marin Viloria | Frontend Developer | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='font-poppins text-xl md:text-6xl'>Victor Marin Viloria</h1>
            <ul className=' flex items-center'>
              <li className='cursor-pointer text-2xl'>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} /></li>
              <li><a className='bg-cyan-500 text-white px-4 py-2 rounded-md ml-8' href="#">My CV</a></li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Victor Marin Viloria</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer and Teacher.</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>Frontend Developer specialized in e-learning.
              Drop a line below and let's talk! :)
            </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube/> 
          </div>

          <div className='relative rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden
          md:h-96 md:w-96'>
            <Image src={photo} layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>Services</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Since the beginning of my journey as a developer, 
              I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div>
            <div className="lg:flex gap-10 text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100}></Image>
              <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
              <p className="py-2">Creating elegant designs suited for your design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100}></Image>
              <h3 className="text-lg font-medium pt-8 pb-2">Web Development</h3>
              <p className="py-2">Creating elegant designs suited for your design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100}></Image>
              <h3 className="text-lg font-medium pt-8 pb-2">Web Consulting</h3>
              <p className="py-2">Creating elegant designs suited for your design theory</p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
          <section>
            <div>
              <h3 className='text-3xl py-1'>Portfolio</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>
              Since the beginning of my journey as a developer, 
              I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3"><Image src={web1}
              className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image></div>
              <div className="basis-1/3"><Image src={web2}
              className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image></div>
              <div className="basis-1/3"><Image src={web3}
              className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image></div>
              <div className="basis-1/3"><Image src={web4}
              className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image></div>
              <div className="basis-1/3"><Image src={web5}
              className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image></div>
              <div className="basis-1/3"><Image src={web6}
              className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"></Image></div>
            </div>
          </section>
        </section>
      </main>

      {/* <h1></h1> */}

    </div>
  )
}
